# set 0 if want to use aug or 0 if not
- augmentations:
  - add: 0
  - addelementwise: 0  
  - additivegaussiannoise: 0 
  - additivelaplacenoise: 0
  - additivepoissonnoise: 0
  - addtobrightness: 0   
  - addtohue: 0
  - addtohueandsaturation: 0 
  - addtosaturation: 0   
  - affine: 1  
  - allchannelsclahe: 0
  - allchannelshistogramequalization: 0
  - averageblur: 0
  - averagepooling: 0  
  - bilateralblur: 0 
  - canny: 0 
  - cartoon: 0   
  - changecolortemperature: 0  
  - clahe: 0 
  - clouds: 0  
  - coarsedropout: 0 
  - coarsepepper: 0
  - coarsesalt: 0
  - coarsesaltandpepper: 0   
  - contrastnormalization: 0 
  - crop: 1
  - cropandpad: 1
  - cutout: 1
  - directededgedetect: 0
  - dropout: 1   
  - edgedetect: 0  
  - elastictransformation: 0 
  - emboss: 0  
  - fastsnowylandscape: 0   
  - fliplr: 1  
  - flipud: 1  
  - fog: 0   
  - gammacontrast: 0 
  - gaussianblur: 0
  - grayscale: 0 
  - histogramequalization: 0 
  - impulsenoise: 0
  - invert: 0  
  - jpegcompression: 0   
  - kmeanscolorquantization: 0   
  - linearcontrast: 0  
  - logcontrast: 0   
  - maxpooling: 0  
  - meanshiftblur: 0 
  - medianblur: 0  
  - medianpooling: 0 
  - minpooling: 0  
  - motionblur: 0  
  - multiply: 0
  - multiplyandaddtobrightness: 0  
  - multiplybrightness: 0  
  - multiplyelementwise: 0
  - multiplyhue: 0   
  - multiplyhueandsaturation: 0   
  - multiplysaturation: 0  
  - pad: 0   
  - pepper: 0  
  - perspectivetransform: 0
  - piecewiseaffine: 0
  - posterize: 0 
  - rain: 0
  - removesaturation: 0  
  - rot90: 0   
  - rotate: 1   
  - salt: 0   
  - saltandpepper: 0
  - scalex: 1  
  - scaley: 1  
  - sharpen: 0   
  - shearx: 1  
  - sheary: 1  
  - sigmoidcontrast: 0  
  - snowflakes: 0
  - solarize: 0
  - translatex: 1
  - translatey: 1
  - uniformcolorquantization: 0   
  - withhueandsaturation: 0